dependencies:
  - geopandas
  - matplotlib
  - shapely
  - seaborn
  - yaml
  - pandas
  - xlrd
  - numpy
  - pathlib
  - bokeh
  - requests
  - pip
  - pip:
    - nbserverproxy
    - jupyter-server-proxy
